from soc.explain.llm_base import BaseLLM


class MockLLM(BaseLLM):
    """
    Simple mock LLM for testing the explanation pipeline
    before connecting a real model.
    """

    def generate(self, prompt: str) -> str:
        return (
            "These recommendations were selected because they appear to align "
            "with the requested category and show a generally consistent visual "
            "style with the outfit. The suggested items seem to support a balanced "
            "and coordinated look based on the available recommendation signals. "
            "This explanation is currently generated by a mock LLM backend."
        )
